version: 2
updates:
  - package-ecosystem: "pip" # For your Python Backend
    directory: "/agent"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # For your Docker images
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
